modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Asecave/weirdcontraptionfinalgoal/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#[modproperties.modId]
#    configuredBackground="minecraft:textures/block/hay_block_top.png"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json"
logoFile="weirdcontraptionfinalgoal-mod-icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${ mod_id }]]
    modId = "create"
    mandatory = true
    versionRange = "${create_version_range}"
    ordering = "NONE"
    side = "BOTH"
    
[[dependencies.${ mod_id }]]
    modId = "biofactory"
    mandatory = false
    versionRange = "${biofactory_version_range}"
    ordering = "NONE"
    side = "BOTH"
    
#[[dependencies.${ mod_id }]]
#    modId = "tfmg"
#    mandatory = false
#    versionRange = "${create_tfmg_version_range}"
#    ordering = "NONE"
#    side = "BOTH"
    
[[dependencies.${ mod_id }]]
    modId = "create_deep_dark"
    mandatory = false
    versionRange = "${create_deep_dark_version_range}"
    ordering = "NONE"
    side = "BOTH"
    
[[dependencies.${ mod_id }]]
    modId = "create_enchantment_industry"
    mandatory = false
    versionRange = "${create_enchantment_industry_version_range}"
    ordering = "NONE"
    side = "BOTH"